import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //documentSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  tutorialSidebar: [
    // {
    //   type: 'doc',
    //   id: 'index',
    //   label: 'Trang Chủ',
    // }, Bai-01-Gioi-Thieu-Lap-Trinh-Dart
    {
      type: 'doc',
      id: 'Bai-01-Gioi-Thieu-Lap-Trinh-Dart',
      label: '1. Giới thiệu lập trình Dart',
    },
    {
      type: 'doc',
      id: 'Bai-02-Bien-Kieu-Du-Lieu-Dart',
      label: '2. Biến và kiểu dữ liệu Dart',
    },
    {
      type: 'doc',
      id: 'Bai-03-Dieu-kien-if-else',
      label: '3. Điều kiện if-else',
    },
    {
      type: 'doc',
      id: 'calculator-tutorial',
      label: 'Simple Calculator',
    },
    {
      type: 'doc',
      id: 'networking-part1',
      label: 'Networking phần 1',
    },
    {
      type: 'doc',
      id: 'networking-part2',
      label: 'Networking phần 2',
    },
    {
      type: 'doc',
      id: 'supabase',
      label: 'Connecting to Supabase',
    },
    {
      type: 'doc',
      id: 'navigation-pattern',
      label: 'Flutter Navigation Pattern',
    },
    {
      type: 'doc',
      id: 'git-flow-team-beginner',
      label: 'Hướng dẫn Git Flow cho làm việc nhóm',
    },
  ],

};

export default sidebars;
