import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //documentSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  tutorialSidebar: [
    // {
    //   type: 'doc',
    //   id: 'index',
    //   label: 'Trang Chủ',
    // }, Bai-01-Gioi-Thieu-Lap-Trinh-Dart
    {
      type: 'doc',
      id: 'Bai-01-Gioi-Thieu-Lap-Trinh-Dart',
      label: '1. Giới thiệu lập trình Dart',
    },
    {
      type: 'doc',
      id: 'Bai-02-Bien-Kieu-Du-Lieu-Dart',
      label: '2. Biến và kiểu dữ liệu Dart',
    },
    {
      type: 'doc',
      id: 'Bai-03-Dieu-kien-if-else',
      label: '3. Điều kiện if-else',
    },
    {
      type: 'doc',
      id: 'Bai-04-Vong-lap-co-ban',
      label: '4. Vòng lặp',
    },
    {
      type: 'doc',
      id: 'Bai-06-function',
      label: '6. Hàm trong Dart',
    },
  ],

};

export default sidebars;
